package com.snakesafe.enums;

public enum CaseStatus {
    CREATED,
    LOCATION_CONFIRMED,
    SNAKE_IDENTIFICATION_PENDING,
    SNAKE_IDENTIFIED,
    BITE_ASSESSMENT_COMPLETE,
    HOSPITAL_SELECTED,
    EMERGENCY_REQUESTED,
    HOSPITAL_ACCEPTED,
    HOSPITAL_REJECTED,
    AMBULANCE_REQUESTED,
    AMBULANCE_ASSIGNED,
    AMBULANCE_EN_ROUTE,
    PATIENT_PICKED_UP,
    PATIENT_ARRIVED,
    TREATMENT_STARTED,
    COMPLETED,
    CANCELLED
}
